FROM python:3.10

WORKDIR /app

COPY web /app

RUN apt-get update && apt-get install -y vim

RUN pip3 install --upgrade pip --default-timeout=1000

RUN pip3 --no-cache-dir install --default-timeout=1000

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["app.py"]
